def load_project_mappings() -> list[dict[str, str]]: ...
def get_qfield_codes() -> list[str]: ...
def get_botavista_codes() -> list[str]: ...
def get_garden_names() -> list[str]: ...
def get_qfield_code_from_botavista_code(botavista_code: str) -> str: ...
def get_garden_names_from_qfield_code(qfield_code: str) -> str: ...